version: '3.8'

services:
  enter-data:
    build: ./enter-data
    ports:
      - "5000:5000"
    depends_on:
      - mysql-db
      - authentication-service

  show-results:
    build: ./show-results
    ports:
      - "5001:5001"
    depends_on:
      - mongo-db
      - authentication-service

  authentication-service:
    build: ./authentication-service
    ports:
      - "5002:5002"

  analytics-service:
    build: ./analytics-service
    ports:
      - "5003:5003"
    depends_on:
      - mysql-db
      - mongo-db

  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: data_db
    ports:
      - "3306:3306"

  mongo-db:
    image: mongo:4.4
    ports:
      - "27017:27017"