name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install -r enter-data/requirements.txt
          pip install -r show-results/requirements.txt
          pip install -r authentication-service/requirements.txt
          pip install -r analytics-service/requirements.txt

      - name: Run Tests
        run: echo "Run your tests here"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Wait for MySQL and MongoDB to be ready
        run: |
          echo "Starting MySQL and MongoDB..."
          docker-compose up -d mysql-db mongo-db

          # Wait for MySQL to be ready
          echo "Waiting for MySQL to start..."
          until docker exec mysql-db mysqladmin --user=root --password=root --host="localhost" --silent ping; do
            echo "MySQL is not ready, waiting..."
            sleep 5
          done
          echo "MySQL is ready!"

          # Wait for MongoDB to be ready
          echo "Waiting for MongoDB to start..."
          until docker exec mongo-db mongo --eval "print('MongoDB is ready')" --quiet; do
            echo "MongoDB is not ready, waiting..."
            sleep 5
          done
          echo "MongoDB is ready!"

      - name: Deploy Containers
        run: |
          echo "Deploying containers..."
          docker-compose up -d --build