name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push enter-data Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./enter-data
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/enter-data:latest

      - name: Build and push show-results Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./show-results
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/show-results:latest

      - name: Build and push authentication-service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./authentication-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/authentication-service:latest

      - name: Build and push analytics-service Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./analytics-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/analytics-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Deploy using Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for services to start (optional)
        run: sleep 30 

      - name: Verify deployment (optional)
        run: |
          curl -s http://localhost:5000/enter # Test your API here
          curl -s http://localhost:5001/results # Test the results API
