name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker --version
          # Install Docker Compose
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install -r enter-data/requirements.txt
          pip install -r show-results/requirements.txt
          pip install -r authentication-service/requirements.txt
          pip install -r analytics-service/requirements.txt

      - name: Run Tests
        run: echo "Run your tests here"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Wait for MySQL and MongoDB
        run: |
          echo "Waiting for MySQL and MongoDB to start"
          sudo docker-compose up -d mysql-db mongo-db
          sleep 30  # Wait for databases to be fully ready

      - name: Deploy Containers
        run: |
          sudo docker-compose up -d --build
