name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker --version
          # Install Docker Compose
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install -r enter-data/requirements.txt
          pip install -r show-results/requirements.txt
          pip install -r authentication-service/requirements.txt
          pip install -r analytics-service/requirements.txt

      - name: Run Tests
        run: echo "Run your tests here"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Wait for MySQL and MongoDB to be ready
        run: |
          echo "Starting MySQL and MongoDB..."
          sudo docker-compose up -d mysql-db mongo-db

          # Wait for MySQL to be ready
          echo "Waiting for MySQL to start..."
          until sudo docker exec mysql-db mysqladmin --user=root --password=root --host="localhost" --silent ping; do
            echo "MySQL is not ready, waiting..."
            sleep 5
          done
          echo "MySQL is ready!"

          # Wait for MongoDB to be ready
          echo "Waiting for MongoDB to start..."
          until sudo docker exec mongo-db mongo --eval "print('MongoDB is ready')" --quiet; do
            echo "MongoDB is not ready, waiting..."
            sleep 5
          done
          echo "MongoDB is ready!"

      - name: Deploy Containers
        run: |
          echo "Deploying containers..."
          sudo docker-compose up -d --build
